config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'search', to: 'pages#search'

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'registration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resource :dashboard, only: [:show] 
  resources :users, only: [:show ] do
    member do 
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch 'update_phone_number' => 'users#update_phone_number'
    end
  end
     resources :rooms, only: [:index, :show] do
      resources :reservations, only: [:create]  
      
      
    end

    get '/your_bookings' => 'reservations#your_bookings'
  namespace :host do
  resources :rooms, only: [:new, :create, :edit, :show, :update, :destroy, :index] do
    member do
    get 'preload'
    get 'preview'
    get 'photo_upload'

  end

      resources :amenities, only: [:new, :create]
      resources :photos, only: [:create, :destroy]
    end


  end
    resources :guest_reviews, only: [:create, :destroy]
    resources :host_reviews, only: [:create, :destroy]
    resources :reservations, only: [:approve, :decline] do
      member do 
        post '/approve' => "reservations#approve"
        post '/decline' => "reservations#decline"
      end
    end
    
   
   get  'host_calendar' => "calendars#host"
   get '/your_reservations' => 'reservations#your_reservations'
   get '/payment_method' => "users#payment"
   post '/add_card' => "users#add_card"

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  has_many_attached :images
end

app/controllers/host/amenities_controller.rb
class Host::AmenitiesController < ApplicationController
  before_action :set_current_room, except: [:show]

  def new
    @amenity = Amenity.new
    
  end

  def create
    @amenity = @room.amenities.create(amenity_params)
    redirect_to host_room_path(@room)
  end

  def show
  end




  private

  def set_current_room
    @room = Room.find(params[:room_id])
  end

  def amenity_params
    params.require(:amenity).permit(:hometype, :roomtype, :accommodate, :bedroom, :bathroom, :swimming, :air, :tv, :kitchen, :restaurant, :internet)
  end
end

app/controllers/host/photos_controller.rb
class Host::PhotosController < ApplicationController
  before_action :authenticate_user!

  # def new
  #   @room = Room.find(params[:room_id])
  #   @photo = Photo.new
  # end 

  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
       @room.photos.create(image: img)
      end

      @photos = @room.photos
    @photo = @room.photos.create(photo_params)
    redirect_to host_room_path(@room)
  end
 end

  def show
  end

  # def destroy
  #   @photo = Photo.find(params[:id])
  #   @room = @photo.room
  #   @photo.images.first.purge
  #   @photos = Photo.where(room_id: @room.id)
  #   respond_to :js

  # end



  private 

  def photo_params
    params.require(:photo).permit(:caption, images: [])
  end
end

app/controllers/host/rooms_controller.rb
class Host::RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_current_room, except: [:index, :new, :create]
  before_action :require_authorized_for_set_current_room, only: [:show, :photo_upload]


  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
 end

  def show
    @room = Room.find(params[:id])
    @amenity = Amenity.new
    @photos = Photo.new
  end

  def photo_upload
  @photos = @room.photos
  end



  def edit
    if @room.user != current_user
      return render :new, status: :unprocessable_entity
    end
  end



  def update
    if @room.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end 
    if @room.update_attributes(room_params)
      redirect_to host_room_path(@room), notice: "Listing Updated..."
    else
      render :new, status: :unprocessable_entity
    end
  end


 def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end


  def create
    @room = current_user.rooms.create(room_params)
    if @room.save
      redirect_to host_room_path(@room), notice: "Saved..."
    else 
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @room = Room.find(params[:id])
    if @room.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end 


    @room.destroy
    redirect_to root_path, notice: "Listing Deleted.."
  end


  def preview

    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end


  private

  def is_conflict(start_date, end_date, room)
    check = room.reservations.where("? < start_date AND end_date < ?) AND status = ?", start_date, end_date, 1)
    check.size > 0? true :false
  end


  def require_authorized_for_set_current_room
    redirect_to root_path, alert: "You don't have permission" unless @room.user.id == current_user.id
  end



  def set_current_room
    @room = Room.find(params[:id])
  end



  def room_params
    params.require(:room).permit(:listing_name, :description, :address, :home_type, :room_type, :adult, :kids, :bedroom, :bathroom, :rate, :web_url, :video, :thumbnail, :instant, images: [])
  end
end

app/helpers/host/amenities_helper.rb
module Host::AmenitiesHelper
end

app/helpers/host/photos_helper.rb
module Host::PhotosHelper
end

app/helpers/host/rooms_helper.rb
module Host::RoomsHelper
   
end

app/views/host/photos/_photos.html.erb
<div class="container"> 
<div class="row">
<% @room.photos.each do |photo| %>
<% if photo.images.attached? %>
<% (0...photo.images.count).each do |image| %>
<div class="col-md-4">
<div class="card test-white">
<%= image_tag(photo.thumbnail(image)) %>
<div class="card-body"> 
<%= photo.caption %>
</div>
</div>
</div>
<% end %>
<% end %>
<% end %>
</div>
</div>
   

   

app/views/host/photos/_photos_list.html.erb
<div class="container">

<% if @room.images.attached? %>
<div class="row">
<% @room.images.each do |image| %>
<div class="col-md-4">
<div class="card">
<div class="card-header">
<%= image_tag image, width: "100%", height: "100%" %>
</div>
<div class="card-footer">
<span class="pull-right">
<%= link_to host_room_path(@room.id, image), remote: true, :onclick => 'remove_image('+image.to_s+')', method: :delete, data: {confirm: "Are you sure you want to delete?"} do %>
<i class="fa fa-trash-o" aria-hidden="true"></i></span>
<% end %>
</div>
</div>
</div> 
<% end %>
</div>
<% end %>
</div> 




<br /><br />







<script>
  function remove_image(id) {
    document.getElementById('photo_'+id).remove();
  }
  
</script>

app/views/host/photos/destroy.js.erb
$('#photos').html("<%= j render 'host/photos/photos_list' %>")

app/views/host/photos/new.html.erb
<div class="container">
 <h1>Enter Your Listing Details</h1>
  <%= simple_form_for @room, url: host_room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
  <%= f.file_field :images, multiple: true, direct_upload: true %><br>
  <%= f.input :caption %>
  <br />
  <%= f.submit 'Add photo', class: 'btn btn-primary' %>
  <% end %>
</div>
</div>


<!--  -->

  <div class="col-md-9">
    <div class="card">

      <div class="card-header">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <!-- PHOTOS UPLOAD GOES HERE -->

              <%= form_for @room, url: host_room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                    <%= f.file_field :images, multiple: true, direct_upload: true %><br>
                    </span>
                  </div>
                </div>

                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-form" %>
                </div>

              <% end %>
            </div>
          </div>

          <div id="photos"><%= render 'host/photos/photos_list' %></div>
        </div>
      </div>

    </div>
  </div>
</div>