config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'search', to: 'pages#search'

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'registration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resource :dashboard, only: [:show] 
  resources :users, only: [:show ] do
    member do 
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch 'update_phone_number' => 'users#update_phone_number'
    end
  end
     resources :rooms, only: [:index, :show] do
      resources :reservations, only: [:create]  
      
      
    end

    get '/your_bookings' => 'reservations#your_bookings'
  namespace :host do
  resources :rooms, only: [:new, :create, :edit, :show, :update, :destroy, :index] do
    member do
    get 'preload'
    get 'preview'
    get 'photo_upload'

  end

      resources :amenities, only: [:new, :create]
      resources :photos, only: [:create, :destroy]
    end


  end
    resources :guest_reviews, only: [:create, :destroy]
    resources :host_reviews, only: [:create, :destroy]
    resources :reservations, only: [:approve, :decline] do
      member do 
        post '/approve' => "reservations#approve"
        post '/decline' => "reservations#decline"
      end
    end
    
   
   get  'host_calendar' => "calendars#host"
   get '/your_reservations' => 'reservations#your_reservations'
   get '/payment_method' => "users#payment"
   post '/add_card' => "users#add_card"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
 validates :fullname, length: {maximum: 35}

        
   has_many :rooms
   has_one_attached :avatar
   has_many :reservations
   has_many :guest_reviews, class_name: "GuestReview", foreign_key: "guest_id"
   has_many :host_reviews, class_name: "HostReview", foreign_key: "host_id"




  def self.from_omniauth(auth)
  user = User.where(email: auth.info.email).first 
  if user
    return user
  else
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.fullname = auth.info.name   
    user.image = auth.info.image 
    user.uid = auth.uid
    user.provider = auth.provider

    # user.skip_confirmation!
  end
 end
end


def generate_pin
  self.pin = SecureRandom.hex(2)
  self.phone_verified = false 
  save      
end

def send_pin
@client = Twilio::REST::Client.new
@client.messages.create(
  from: '+12762212767',
  to: self.phone_number,
  body: "Your pin is #{self.pin}"
  )
 end


def verify_pin(entered_pin)
  update(phone_verified: true) if self.pin == entered_pin
end 

end

 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def show
    @user = User.find(params[:id])
    @rooms = @user.rooms   
    @guest_reviews = Review.where(type: "GuestReview", host_id: @user.id)
    @host_reviews = Review.where(type: "HostReview", guest_id: @user.id)
  end

  def payment
  end 

  def add_card
    if current_user.stripe_id.blank?
      customer = Stripe::Customer.create(
        email: current_user.email
        )

      current_user.stripe_id = customer.id
      current_user.save
    else
      customer = Stripe::Customer.retrieve(current_user.stripe_id)
    end

    month, year = params[:expiry].split(/ \/ /)
    new_token = Stripe::Token.create(:card => {
      :number => params[:number],
      :exp_month => month,
      :exp_year => year,
      :cvc => params[:cvv]
    })

    customer.sources.create(source: new_token.id)

    flash[:notice] = 'Your card is saved'.
    redirect_to payment_method_path
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to payment_method_path   
  end

  def update_phone_number
    current_user.update_attributes(user_params)
    current_user.generate_pin
    current_user.send_pin

    redirect_to edit_user_registration_path, notice: "Saved..."
   rescue Twilio::REST::RestError => e
    redirect_to edit_user_registration_path, alert: "#{e.error_message}"
  end

  def verify_phone_number
    current_user.verify_pin(params[:user][:pin])

    if current_user.phone_verified
      flash[:notice] = "Your phone number is verified."
    else
      flash[:alert] = "Cannot verify your phone number."
    end

    redirect_to edit_user_registration_path

 rescue Twilio::REST::RestError => e
    redirect_to edit_user_registration_path, alert: "#{e.error_message}"
  end


  private


  def user_params
    params.require(:user).permit(:avatar, :phone_number, :pin)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_sidebar.html.erb
    <div class="col-md-4 offset-md-4">
      <ul class="sidebar-list">
        <li class="sidebar-item"><%= link_to "bookings", your_bookings_path, class: "sidebar-link active" %></li>
          <li class="sidebar-item"><%= link_to "Reservations", your_reservations_path, class: "sidebar-link active" %></li>
            <li class="sidebar-item"><%= link_to "Listings", host_rooms_path, class: "sidebar-link active" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/payment.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-4">
      <ul class="sidebar-list">

        <li class="sidebar-item"><%= link_to "Payment Method",payment_method_path, class: "sidebar-link active" %></li>
      </ul>
    </div>



    <div class="box col-md-6">
      <div class="card-header bg-secondary">Add Payment Method</div>
      <div class="card-body">

        <div class="card" style="margin-bottom: 20px"></div>
        <div class="container">

          <%= form_tag("/add_card", method: "post", id: "add-card") do %>
          <div class="row pull-center">
            <div class="col-md-12">
              <div class="well">
                <div class="row">
                  <div class="col-md-6 form-group">
                    <label>Card Number</label>
                    <input type="text" name="number" class="form-control">
                  </div>


                  <div class="col-md-4 form-group">
                    <label>Expiration</label>
                    <input type="text" placeholder="MM/YY" name="expiry" class="form-control">
                  </div>
                </div>


                <div class="row">
                  <div class="col-md-6 form-group">
                    <label>Name</label>
                    <input type="text" name="name" class="form-control">
                  </div>

                  <div class="col-md-4 form-group">
                    <label>CVV</label>
                    <input type="text" name="CVV" class="form-control">
                  </div>
                </div>


                <div class="row">
                  <div class="col-md-12 text-right">
                    <% if current_user.stripe_id.blank? %>
                    <button class="btn btn-danger btn-block">Add Card</button>
                    <% else %>

                    <button class="btn btn-primary btn-block">Update Card</button>
                  </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>
</div>
</div>
</div>









<script>
  $(function() {
    var card = new Card({
      form: '#add-card',
      container: '.card'
    })
  });
</script>

app/views/users/show.html.erb
<hr />
<div class="container">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <div class="card" style="width:300px">
          <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, class: "avatar2" %>
          <% else %>
          <%= image_tag gravatar_image_url(current_user.email), class: "avatar2" %>
          <% end %>
          <div class="card-body">
            <h4><%= @user.fullname %></h4>
            Member Since: <%= @user.created_at.strftime("%B %d, %Y") %>
          </div>
          <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-dark btn-block" %>
        </div>
      </div>

      <div class="col-md-4"><br />
        <div class="box">
          <h3 class="text-center">About me</h3>
          <br />
          <h5 class="text-center">Contact</h5>
          <p class="text-center"><%= @user.email %>
            <br /><%= @user.phone_number%></p>
          </div>
        </div>

        <div class="col-md-4">
          <%= render 'users/sidebar' %>
        </div>
      </div>
    </div>
  </div>


  <div class="container"> 
    <h3 class="text-center">Your Listings</h3><br />
    <div class="row">
      <% @rooms.each do |room| %>
      <div class="col-md-6">
        <div class="card"> 
          <% if room.images.attached? %><%= image_tag room.images.first, width: "100%", height: "100%" %>
          <% end %> 
          <div class="card-body"> 
            <p><%= room.listing_name %></p>
            <%= link_to "Update", host_room_path(room), class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>


  <div class="container">
    <h6 class="text-center">Reviews from Guest (<%= @guest_reviews.count %>)</h6>
    <%= render "reviews/guest_list" %>
  </div>



  <div class="container">
    <h6 class="text-center">Reviews from Host (<%= @host_reviews.count %>)</h6>
    <%= render "reviews/host_list" %>
  </div>
</div>
</div>