config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'search', to: 'pages#search'

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'registration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resource :dashboard, only: [:show] 
  resources :users, only: [:show ] do
    member do 
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch 'update_phone_number' => 'users#update_phone_number'
    end
  end
     resources :rooms, only: [:index, :show] do
      resources :reservations, only: [:create]  
      
      
    end

    get '/your_bookings' => 'reservations#your_bookings'
  namespace :host do
  resources :rooms, only: [:new, :create, :edit, :show, :update, :destroy, :index] do
    member do
    get 'preload'
    get 'preview'
    get 'photo_upload'

  end

      resources :amenities, only: [:new, :create]
      resources :photos, only: [:create, :destroy]
    end


  end
    resources :guest_reviews, only: [:create, :destroy]
    resources :host_reviews, only: [:create, :destroy]
    resources :reservations, only: [:approve, :decline] do
      member do 
        post '/approve' => "reservations#approve"
        post '/decline' => "reservations#decline"
      end
    end
    
   
   get  'host_calendar' => "calendars#host"
   get '/your_reservations' => 'reservations#your_reservations'
   get '/payment_method' => "users#payment"
   post '/add_card' => "users#add_card"

end

app/models/amenity.rb
class Amenity < ApplicationRecord
  validates :hometype, presence: true
  validates :roomtype, presence: true
  validates :bedroom, presence: true
  validates :accommodate, presence: true
 
  belongs_to :room
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :room
  belongs_to :reservation
  belongs_to :guest
  belongs_to :host
end

app/models/guest_review.rb
class GuestReview < Review
  belongs_to :guest, class_name: "User"
end

app/models/host_review.rb
class HostReview < Review
    belongs_to :host, class_name: "User"
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room
  has_many_attached :images
end

app/models/reservation.rb
class Reservation < ApplicationRecord
 enum status: {Waiting: 0, Approved: 1, Declined: 2}
  belongs_to :user
  belongs_to :room
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  # belongs_to :room
  # belongs_to :reservation
  # belongs_to :guest
  # belongs_to :host
end

app/models/room.rb
class Room < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  has_many :amenities
  geocoded_by :address
  after_validation :geocode
  has_many :photos
  has_many_attached :images
  has_many :reservations
  has_many :guest_reviews
  has_one_attached :video
  has_one_attached :thumbnail

  validates :home_type, presence: true
  validates :bathroom, presence: true
  validates :bedroom, presence: true
  validates :adult, presence: true

  # def thumbnail input
 #    return self.images[input].variant(resize: "1200x500").processed
 #  end


def average_rating
  guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
 validates :fullname, length: {maximum: 35}

        
   has_many :rooms
   has_one_attached :avatar
   has_many :reservations
   has_many :guest_reviews, class_name: "GuestReview", foreign_key: "guest_id"
   has_many :host_reviews, class_name: "HostReview", foreign_key: "host_id"




  def self.from_omniauth(auth)
  user = User.where(email: auth.info.email).first 
  if user
    return user
  else
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0, 20]
    user.fullname = auth.info.name   
    user.image = auth.info.image 
    user.uid = auth.uid
    user.provider = auth.provider

    # user.skip_confirmation!
  end
 end
end


def generate_pin
  self.pin = SecureRandom.hex(2)
  self.phone_verified = false 
  save      
end

def send_pin
@client = Twilio::REST::Client.new
@client.messages.create(
  from: '+12762212767',
  to: self.phone_number,
  body: "Your pin is #{self.pin}"
  )
 end


def verify_pin(entered_pin)
  update(phone_verified: true) if self.pin == entered_pin
end 

end

 

app/controllers/pages_controller.rb
class PagesController < ApplicationController



  def index
    @rooms = Room.limit(4)
  end

def search
if params[:search].present? && params[:search].strip != ""
  session[:loc_search] = params[:search]
end

  arrResult = Array.new

  if session[:loc_search] && session[:loc_search] != ""
    @rooms_address = Room.near(session[:loc_search], 5, order: 'distance')
  else
   @rooms_address = Room.all
  end

  @search = @rooms_address.ransack(params[:q])
  @rooms = @search.result


  @arrRooms = @rooms.to_a

  if (params[:start_date] && params[:end_date] && !params[:start_date].empty? && !params[:end_date].empty?)
    start_date = Date.parse(params[:start_date])
     end_date = Date.parse(params[:end_date])

     @rooms.each do |room|

      not_available = room.reservations.where(
        "(? <= start_date AND start_date <= ?)
      OR (? <= end_date AND end_date <= ?)
      OR (start_date <? AND ? < end_date))
      AND status = ?",
      start_date, end_date,
      start_date, end_date,
      start_date, end_date,
      1
      ).limit(1)

      if not_available.length > 0
        @arrRooms.delete(room)
      end
    end
  end
  end



end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.paginate(page: params[:page])
  end

  def show
    @room = Room.find(params[:id])
     @guest_reviews = @room.guest_reviews
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  

#     def avatar_url(user)
#       if user.avatar.attached?
#         "http://graph.facebook.com/#{user.uid}/picture?type=large"
#       else
#         gravatar_id = Digest::MD5.hexdigest(user.email).downcase
#         "https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&150"
#   end
# end

def avatar_for(user, options = {size: 40})
  if user.avatar.attached?
    "http://graph.facebook.com/#{user.uid}/picture?type=large"
  else
    gravatar_id = Digest::MD5::hexdigest(user.email).downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "rounded-circle")
  end
end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">


<footer class="page-footer font-small special-color-dark pt-4">
  <div class="container">
    <div class="row">
      <div class="col-md-6 mb-4">

        <!-- Form -->
        <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
          <div class="form-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>
          </div>
      <% end %>
       
      </div>
         <div class="col-md-6 mb-4">
   <%= link_to 'https://facebook.com/hospitality9ja' do %>
        <span class="fa fa-facebook-square social-button"><p class="text-white">Follow us on facebook</p></span>
      <% end %>
    </div>
      
      
      </div>
    </div>

  </div>



  <div class="footer-copyright text-center py-3"> Hospitality9ja © 2020


</footer>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar" style="background-color:  #ab150a; padding: 0px;">
  <div class="container">

   <!--  <%= image_tag 'logo.png' %> -->
    <%= link_to 'Tripsort', root_path, class: 'navbar-brand' %>
   
   


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav mr-auto"><li class="nav-item active"></li></ul>



      <ul class="navbar-nav navbar-right">
         <li class="nav-item active"></li>

        <% if !user_signed_in? %>
        <li class="nav-item active">  
          <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
        </li>


        <li class="nav-item link active">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>

          <% else %>


          <li class="nav-item dropdown active">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "rounded-circle", size: 40 %>
              <% else %>
              <%= image_tag gravatar_image_url(current_user.email), class: "rounded-circle",size: 40 %>
              <% end %>
              Hi, <%= current_user.fullname%> <span class="caret"></span>

            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to "My Dashboard", dashboard_path %></li>
              <li><%= link_to "My Profile", user_path(current_user) %></li>
              <div class="dropdown-divider"></div>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
               <li><%= link_to "Account Settings", payment_method_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
            </ul>
            <% end %>
          </li>   
        </ul> 
        <%= link_to new_host_room_path, class: 'btn btn-success host' do %>
          Become a host
          <% end %>
      </div>
    </nav>
    
    <% if (user_signed_in?) && !current_page?(root_path) && !current_page?("/rooms/#{params[:id]}") %>

    <nav class="navbar navbar-expand navbar-dark"style="background-color: #3e2723;">
          <div class="container">
        <ul class="navbar-nav">
           <% if current_page?(dashboard_path) %>
              <li class="nav-item"> 
            <%= link_to "My Dashboard", dashboard_path, class: 'nav-link' %>
            <% end %>
              </li>
             
              <li class="nav-item-active ">
                <%= link_to "Manage Listing", host_rooms_path, class: 'nav-link' %>
              </li>
               </ul>
             </div>
           </nav>

            <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tripsort</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

   <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDVI2DOGtO42Xt_-e9elvVoFH2vL0WyaMI&libraries=places"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     
  
     <link href="https://vjs.zencdn.net/7.6.5/video-js.css" rel="stylesheet">
    
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/ui-darkness/jquery-ui.css">


    
    
  </head>

  <body>
  <%= render "layouts/navbar" %>

  <%= render "devise/shared/flash" %>

 <div id="flex-content-container">
    <%= yield %>
      
  </div>
 

   <%= render "layouts/footer" %>
     <script src='https://vjs.zencdn.net/7.6.0/video.js'></script>
    <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
        

  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron jumbotron-fluid" style="background-color: #F2F2F2;">
  <div class="container">
   <h3><span class="red">Luxury</span> Rentals For Short Staycation..</h3><p>Experience hospitality like never before!</p>


<div class="col-12">
      <%= form_tag search_path, method: :get do %>
    <div class="row">
      <div class="col-md-4 search">
        <%= text_field_tag :search, params[:search], placeholder: 'Where are you going?   e.g,  New York', class: "form-control search", id: "autolocation"%><br />
      </div>
      <div class="col-md-3 search">
        <%= text_field_tag :start_date, params[:start_date], placeholder: "Check In", class: "form-control datepicker search" %><br />
      </div>
      <div class="col-md-3 search ">
        <%= text_field_tag :end_date, params[:start_date], placeholder: "Check Out", class: "form-control datepicker search" %>
        <br />
      </div>
      <div class="col-md-2 search">
        <%= submit_tag "Search", class: " form-control search btn btn-dark" %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>


     <div class="container">
    <div class="col-md-12 luxury"style="background-image: url(/assets/couple.jpg); padding-top: 20px;">
       <div class="text-white text-center"><h2>Plan Your Dream Vacation</h2>


     </div>
   </div>
 </div>
</div>     
  <br /><br />


   <div class="container">
  <div class="box row">
    <%= render "host/rooms/list_room" %>
  </div>
</div>
<br /><br />


 <div class="container">
       <div class="col-md-12 luxury1" style="padding-top: 50px;">
         <div class="text-center text-white"><h2>Do you own a luxurious accommodation?</h2>
       <p class="text-center text-white">Hotel-Resort-Home</p>
       <p>Upload Your Listing to Get Bookings</p>
          <% if !user_signed_in? %>
        <%= link_to 'Sign up and become a host', new_user_registration_path, class: 'btn btn-danger ' %></li><br />
        <% else %>
       <%= link_to 'Sign up and become a host', new_host_room_path, class: 'btn btn-danger ' %></li><br />
        <% end %>
      </div>
       </div>
     </div>
   </div>
   <br /><br />


  <div class="container">
  <h3>Top Destinations To Explore</h3><br />
    <div class="row">
      <div class="col-md-3 col-sm-12">
        <a href="https://capstone-project-ruky-a.herokuapp.com/search?utf8=%E2%9C%93&search=paris">
          <div class="paris-card"></div>
        </a>
      </div>

      <div class="col-md-3 col-sm-12">
        <a href="https://capstone-project-ruky-a.herokuapp.com/search?utf8=%E2%9C%93&search=miami"> <div class="miami-card"></div>
        </a>
      </div>

      <div class="col-md-3 col-sm-12">
        <a href="https://capstone-project-ruky-a.herokuapp.com/search?utf8=%E2%9C%93&search=los angeles"> <div class="lasvegas-card"></div>
        </a>
      </div>

      <div class="col-md-3 col-sm-12">
        <a href="https://capstone-project-ruky-a.herokuapp.com/search?utf8=%E2%9C%93&search=london">
          <div class="london-card"></div>
        </a>
      </div>
    </div>
  </div>
  <br />


  <script>
    $('#start_date').datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      maxDate: '6m',
      onSelect: function(selected) {
        $('#end_date').datepicker("option", "minDate", selected);
        $('#end_date').attr("disabled", false);

      }
    });


    $('#end_date').datepicker({
      dateFormat: 'dd-mm-yy',
      minDate: 0,
      maxDate: '6m',
      onSelect: function(selected) {
        $('#start_date').datepicker("option", "maxDate", selected);   

      }
    });
  </script>
   

    <script src="/javascripts/jquery.min.js" type="text/javascript"></script> <script src="/javascripts/jquery.geocomplete.min.js" type="text/javascript"></script> <script type="text/javascript"> $("#autolocation").geocomplete({ details: ".geo-details", detailsAttribute: "data-geo" }); </script>

app/views/pages/search.html.erb
<div class ="boxes">

  <div class="row">
    <div class="col-md-6">
      <button id="filter" class="btn btn-outline" data-toggle="collapse" data-target="#collapseCard">
        Advanced filters <i class="fa fa-chevron-down"></i>
      </button>
    </div><br /><br />



    <div class="row">
      <br/>
      <div class="collapse" id="collapseCard">

        <%= search_form_for @search, url: search_path, remote: true do |f| %>
        <div class="box">
          <div class="row">
            <div class="col-md-6">
              <label>Rate range:</label>
              <div id="slider-range"></div>
            </div>
            <div class="col-md-3">
              <label>Min price:</label>
              <%= f.text_field :rate_gteq, class: "form-control" %>
            </div>
            <div class="col-md-3">
              <label>Max price:</label>
              <%= f.text_field :rate_lteq, class: "form-control" %>
            </div>
          </div>
          <br/>

          <div class="row">
            <div class="col-md-6">
              <%= text_field_tag :start_date, params[:start_date], readonly: true, placeholder: "Start Date", class: "form-control datepicker" %>
            </div>
            <div class="col-md-6">
              <%= text_field_tag :end_date, params[:end_date], readonly: true, placeholder: "End Date", class: "form-control datepicker" %>
            </div>
          </div>
          <br/>

          <div class="row">
            <div class="col-md-4">
              <%= check_box_tag "q[roomtype_eq_any][]", "Entire" %> Hotel
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[hometypetype_eq_any][]", "Private" %> Home
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[hometype_eq_any][]", "Shared" %> Resort
            </div>
          </div>
          <br/>



          <div class="row">
            <div class="col-md-4">
              <%= check_box_tag "q[tv_eq]", true %> TV
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[kitchen_eq]", true %> Kitchen
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[Internet_eq]", true %> Internet
            </div>
            <div class="col-md-4">
              <%= check_box_tag "q[restaurant_eq]", true %> Heating
            </div>
            <div class="col-md-8">
              <%= check_box_tag "q[air_eq]", true %> Air Conditioning
            </div>
          </div>
          <hr/>

          <div class="text-center">
            <%= f.submit "Search", class: "btn btn-danger" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <br />
    <div class="container">
      <div class="row" id="list_room">
        <%= render partial: 'host/rooms/room_list', locals: {rooms: @arrRooms}  %>
      </div>
    </div>
  </div>
</div>






<div class="box col-md-8 boxes">
  <div id="map">
  </div>

  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDVI2DOGtO42Xt_-e9elvVoFH2vL0WyaMI&callback=initMap">
</script>
<script>
  function initialize(rooms) {
    var location = {lat: 27.8769072, lng: -82.3461322}

    if (rooms.length > 0) {
      location = {lat: rooms[0].latitude, lng: rooms[0].longitude}
    }

    var map = new google.maps.Map(document.getElementById('map'), {
      center: location,
      zoom: 12
    });

    var marker, inforwindow;

    rooms.forEach(function(room) {
      marker = new google.maps.Marker({
        position: {lat: room.latitude, lng: room.longitude},
        map: map
      });

      inforwindow = new google.maps.InfoWindow({
        content: "<div id='content'>$" + room.rate + "</div>"
      });

      inforwindow.open(map, marker);
    })
  }

  google.maps.event.addDomListener(window, 'load', function() {
    initialize(<%= raw @arrRooms.to_json %>)
  });
</script>
</div>
</div>



<br />
<script>
  $(function() {
    $("#q_rate_gteq").val('50');
    $("#q_rate_lteq").val('500');

    $("#slider-range").slider({
      range: true,
      min: 0,
      max: 1000,
      values: [100, 500],
      slide: function(event, ui) {
        $("#q_rate_gteq").val(ui.values[0]);
        $("#q_rate_lteq").val(ui.values[1]);

      }
    });

    $(".ui-widget-header").css('background', ' #103D65');
    $(".ui-state-default, .ui-widget-content").css('background', 'white');
    $(".ui-state-default, .ui-widget-content").css('border-color', '#103D65');
  })
</script>





<br />


<script>
  $('#start_date').datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#end_date').datepicker("option", "minDate", selected);
      $('#end_date').attr("disabled", false);
    }
  });

  $('#end_date').datepicker({
    dateFormat: 'dd-mm-yy',
    minDate: 0,
    maxDate: '3m',
    onSelect: function(selected) {
      $('#start_date').datepicker("option", "maxDate", selected);
    }
  });

  var open = true;
  $('#filter').click(function() {
    if (open) {
      $('#filter').html("Advanced filters <i class='fa fa-chevron-up'></i>")

    } else {
      $('#filter').html("Advanced filters <i class='fa fa-chevron-down'></i>")
    }

    open = !open;
  });



</script>


</div>
</div>
<br />

app/views/pages/search.js.erb
$('#list_room').html('<%= j render partial: "host/rooms/list_room", locals: {rooms: @arrRooms}  %>')
initialize(<%= raw @arrRooms.to_json %>)