config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'search', to: 'pages#search'

  devise_for :users,
  path: '',
  path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'registration'},
  controllers: {omniauth_callbacks: 'omniauth_callbacks'}

  resource :dashboard, only: [:show] 
  resources :users, only: [:show ] do
    member do 
      post '/verify_phone_number' => 'users#verify_phone_number'
      patch 'update_phone_number' => 'users#update_phone_number'
    end
  end
     resources :rooms, only: [:index, :show] do
      resources :reservations, only: [:create]  
      
      
    end

    get '/your_bookings' => 'reservations#your_bookings'
  namespace :host do
  resources :rooms, only: [:new, :create, :edit, :show, :update, :destroy, :index] do
    member do
    get 'preload'
    get 'preview'
    get 'photo_upload'

  end

      resources :amenities, only: [:new, :create]
      resources :photos, only: [:create, :destroy]
    end


  end
    resources :guest_reviews, only: [:create, :destroy]
    resources :host_reviews, only: [:create, :destroy]
    resources :reservations, only: [:approve, :decline] do
      member do 
        post '/approve' => "reservations#approve"
        post '/decline' => "reservations#decline"
      end
    end
    
   
   get  'host_calendar' => "calendars#host"
   get '/your_reservations' => 'reservations#your_reservations'
   get '/payment_method' => "users#payment"
   post '/add_card' => "users#add_card"

end

app/models/room.rb
class Room < ApplicationRecord
  enum instant: {Request: 0, Instant: 1}
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  has_many :amenities
  geocoded_by :address
  after_validation :geocode
  has_many :photos
  has_many_attached :images
  has_many :reservations
  has_many :guest_reviews
  has_one_attached :video
  has_one_attached :thumbnail

  validates :home_type, presence: true
  validates :bathroom, presence: true
  validates :bedroom, presence: true
  validates :adult, presence: true

  # def thumbnail input
 #    return self.images[input].variant(resize: "1200x500").processed
 #  end


def average_rating
  guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
end

end

app/controllers/host/amenities_controller.rb
class Host::AmenitiesController < ApplicationController
  before_action :set_current_room, except: [:show]

  def new
    @amenity = Amenity.new
    
  end

  def create
    @amenity = @room.amenities.create(amenity_params)
    redirect_to host_room_path(@room)
  end

  def show
  end




  private

  def set_current_room
    @room = Room.find(params[:room_id])
  end

  def amenity_params
    params.require(:amenity).permit(:hometype, :roomtype, :accommodate, :bedroom, :bathroom, :swimming, :air, :tv, :kitchen, :restaurant, :internet)
  end
end

app/controllers/host/photos_controller.rb
class Host::PhotosController < ApplicationController
  before_action :authenticate_user!

  # def new
  #   @room = Room.find(params[:room_id])
  #   @photo = Photo.new
  # end 

  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
       @room.photos.create(image: img)
      end

      @photos = @room.photos
    @photo = @room.photos.create(photo_params)
    redirect_to host_room_path(@room)
  end
 end

  def show
  end

  # def destroy
  #   @photo = Photo.find(params[:id])
  #   @room = @photo.room
  #   @photo.images.first.purge
  #   @photos = Photo.where(room_id: @room.id)
  #   respond_to :js

  # end



  private 

  def photo_params
    params.require(:photo).permit(:caption, images: [])
  end
end

app/controllers/host/rooms_controller.rb
class Host::RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_current_room, except: [:index, :new, :create]
  before_action :require_authorized_for_set_current_room, only: [:show, :photo_upload]


  def index
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
 end

  def show
    @room = Room.find(params[:id])
    @amenity = Amenity.new
    @photos = Photo.new
  end

  def photo_upload
  @photos = @room.photos
  end



  def edit
    if @room.user != current_user
      return render :new, status: :unprocessable_entity
    end
  end



  def update
    if @room.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end 
    if @room.update_attributes(room_params)
      redirect_to host_room_path(@room), notice: "Listing Updated..."
    else
      render :new, status: :unprocessable_entity
    end
  end


 def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end


  def create
    @room = current_user.rooms.create(room_params)
    if @room.save
      redirect_to host_room_path(@room), notice: "Saved..."
    else 
      render :new, status: :unprocessable_entity
    end
  end


  def destroy
    @room = Room.find(params[:id])
    if @room.user != current_user
      return render plain: 'Not Allowed', status: :forbidden
    end 


    @room.destroy
    redirect_to root_path, notice: "Listing Deleted.."
  end


  def preview

    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end


  private

  def is_conflict(start_date, end_date, room)
    check = room.reservations.where("? < start_date AND end_date < ?) AND status = ?", start_date, end_date, 1)
    check.size > 0? true :false
  end


  def require_authorized_for_set_current_room
    redirect_to root_path, alert: "You don't have permission" unless @room.user.id == current_user.id
  end



  def set_current_room
    @room = Room.find(params[:id])
  end



  def room_params
    params.require(:room).permit(:listing_name, :description, :address, :home_type, :room_type, :adult, :kids, :bedroom, :bathroom, :rate, :web_url, :video, :thumbnail, :instant, images: [])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.paginate(page: params[:page])
  end

  def show
    @room = Room.find(params[:id])
     @guest_reviews = @room.guest_reviews
  end

end

app/helpers/host/amenities_helper.rb
module Host::AmenitiesHelper
end

app/helpers/host/photos_helper.rb
module Host::PhotosHelper
end

app/helpers/host/rooms_helper.rb
module Host::RoomsHelper
   
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/host/rooms/_editmodal.html.erb
<div class="modal fade" id="editlisting" tabindex="-8" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      
        <h4 class="modal-title" id="editlisting">Room details</h4>
      </div>
          <%= simple_form_for @room, url: host_room_path do |f| %>

       <div class="modal-body">
       <%= f.input :listing_name %>
        
            <%= f.input :description  %>
       <br />
          <%= f.input :address %>

        <%= f.input :rate %>
      
       <div class="field">
        <%= f.label :photo %>
      <%= f.file_field :images, multiple: true, direct_upload: true %>
    </div>
    <br />

       <div class="field">
        <%= f.label :video %>
      <%= f.file_field :video %>
    </div>
      
       </div>
         <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       <%= f.submit "Update listing" , class: 'btn btn-primary' %>
        <div id='preview'></div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/host/rooms/_list_room.html.erb
<div class="container">
  <h3>Featured Accommodations</h3>
  <hr  />
  <div class="row">
    <% @rooms.each do |room| %>
    <div class=" col-md-3">
      <div class="card"> 
         <% if room.images.attached? %><%= image_tag room.images.first, width: "100%", height: "180px" %>  
        <% end %>

        <div class="card-body room"> 
         <h6><%= link_to room.listing_name, room_path(room) %>
            <span class="pull-right"> $<%= room.rate %></span></h6>
          
            <div id="star_<%= room.id %>"></div> 
            <%= pluralize(room.guest_reviews.count, "review") %>

       
         </div>
       </div>
       </div>

          <script>
      $('#star_<%= room.id %>').raty({
        path: '/assets',
        readOnly: true,
        score: <%= room.average_rating %>
      });
    </script>
    <% end %>
  </div>
</div>

       

  

app/views/host/rooms/_modal.html.erb
<div class="modal fade" id="photo" tabindex="-3" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      
        <h4 class="modal-title" id="photo">Add Photos</h4>
      </div>
       <%= form_for @room, url: host_room_path(@room) do |f| %>
       <div class="modal-body">
          <%= f.file_field :images, multiple: true, direct_upload: true %>      
       </div>
         <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       <%= f.submit "Add photo" , class: 'btn btn-primary' %>
     </div>
      </div>
      <% end %>
     </div>
   </div>

    

app/views/host/rooms/_room_list.html.erb
<div class="container">
  <div class="row">
    <% @rooms.each do |room| %>
    <div class=" col-md-6">
      <div class="card"> 
         <% if room.images.attached? %><%= image_tag room.images.first, width: "100%", height: "180px" %>  
        <% end %>

        <div class="card-body room"> 
         <h6><%= link_to room.listing_name, room_path(room) %>
            <span class="pull-right"> $<%= room.rate %></span></h6>
           <%= pluralize(room.guest_reviews.count, "review") %><br />
       
         </div>
       </div>
       </div>
    <% end %>
  </div>
</div>

       

app/views/host/rooms/_room_menu.html.erb
<br />
  <div class="text-center">
  <%= link_to 'Add Amenities...', new_host_room_amenity_path(@room), class: 'btn btn-danger btn-sm' %>
  </div>
  <br />

  <div class="text-center">
  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#photo">
  Add photos
  </button>
  </div>
  <br />

  <div class="text-center">
  <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#editlisting">
 Update listing
  </button>
</div><br />


  <div class="text-center">
  <%= link_to 'Delete Listing', host_room_path(@room), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger btn-sm' %> 
  </div>
  <br />


  

app/views/host/rooms/_roomratemodal.html.erb
<div class="modal fade" id="roomrate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      
        <h4 class="modal-title" id="roomrate">Add Rate</h4>
      </div>
       <%= form_for @room, url: host_room_path(@room) do |f| %>
       <div class="modal-body">
          <label>Room Rate</label>
     <%= f.text_field :rate, placeholder: "eg: $100", class: "form-control", required: true %>
             
       </div>
         <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
       <%= f.submit "Add rate" , class: 'btn btn-primary' %>
        <div id='preview'></div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/host/rooms/edit.html.erb
<br />
 <div class="container">
  <div class="row">
 <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
          <div class="card test-white">
         <div class="card-header">
        <h4 class="text-center">Add your Listing Details</h4>
      </div>
     <div class="card-body">
        <%= form_for @room, url: host_room_path do |f| %>
         <%= f.text_field :listing_name, placeholder: "Listing name", class: "form-control", required: true %>
         <br />
         <%= f.text_field :address, placeholder: "Address", class: "form-control", required: true %><br />
         <%= f.text_area :description, rows: 5, placeholder: "Write a brief description of your home", class: "form-control", required: true %>
       <br />
    
            <div class="col-md-4">
                <label>Rate</label>
                <%= f.text_field :rate, placeholder: "eg: $100", class: "form-control", required: true %>
              </div>
              <br />

             <div class="col-md-4">
                <label>Photo</label>
            <%= f.file_field :image %>
          </div>
          <br />

            <div class="text-center">
              <%= f.submit 'Update', class: "btn btn-danger btn-block" %>
            </div>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>



<div class="col-10 offset-1 float-right">
<%= link_to 'Next', new_host_room_amenity_path(@room) %>
</div>
<br />

app/views/host/rooms/index.html.erb
<div class="box col-10 offset-1">
  <div class="row">
    <div class="col-sm-4">
      <% if current_user.avatar.attached? %>
      <%= image_tag current_user.avatar, class: "rounded-circle", size: 120 %>
      <% else %>
      <%= image_tag gravatar_image_url(current_user.email), class: "avatar2" %>
      <% end %>
    </div>

    <div class="col-sm-4"><br />
      <h4><%= current_user.fullname %></h4><br />
      <h5>Member Since: <%= current_user.created_at.strftime("%B %d, %Y") %></h5><br />
      <h6><%= current_user.email %></h6><br />
      <h6><%= current_user.phone_number%></h6>
    </div>



    <div class="col-md-4">
      <ul class="sidebar-list">
        <li class="sidebar-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "sidebar-link active" %></li>
        <li class="sidebar-item"><%= link_to "bookings", your_bookings_path, class: "sidebar-link active" %></li>
          <li class="sidebar-item"><%= link_to "Reservations", your_reservations_path, class: "sidebar-link active" %></li>
      </ul>
    </div>
  </div>
</div>

<br />

  <div class="col-8 offset-2">
     <div class="card">
      <div class="card-header bg-dark">
        <h4 class="text-center">Your Listings</h4>
      </div>
       <div class="card-body">
      <% @rooms.each do |room| %>
  
        <div class="row">
          <div class="col-md-4">
               <p><%= room.listing_name %></p>
            <% if room.images.attached? %><%= image_tag room.images.first, width: "280", height: "180px" %>
         <% end %> 
          </div>
          <div class="col-md-4 offset-md-4"><br />
            <%= link_to "Update", host_room_path(room), class: "btn btn-danger" %>
          </div>
        </div>
        <hr />
        <% end %>
      </div>
    </div>
  </div>
  

app/views/host/rooms/new.html.erb
<!-- Jumbotron -->
<div class="card card-image" style="background-image: url(/assets/building.jpg);">
  <div class="text-white text-center rgba-stylish-strong py-5 px-4">
    <div class="py-5">
      <h5 class="h5 orange-text"><i class="fa fa-camera-retro"></i></h5>
      <h2 class="card-title h2 my-4 py-2"></h2>
      <br />
      <div class="text-center">
        <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#newlisting">
          Upload listing
        </button>
      </div>
    </div>
  </div>
</div>
<br /><br />

<div class="container">
  <div class="row feature text-center">
    <div class="col-12 col-sm">
      <p>Sign Up</p>
    </div>



    <div class="col-12 col-sm">
      <p>Upload Video</p>
    </div>

    <div class="col-12 col-sm">
      <p>Get Bookings</p>
    </div>
  </div>
</div>

</div><br />

<div class="modal fade" id="newlisting" tabindex="-7" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header" style="background-color: #3e2723; color: white;">

        <h4 class="modal-title" id="newlisting">Add listing</h4>
      </div>
      <%= form_for @room, url: host_rooms_path do |f| %>
      <div class="modal-body">
        <div class="form-field">
          <%= f.text_field :listing_name, placeholder: "Listing name", class: "form-control", required: true %>
        </div>
        <br />
        <div class="form-field">
          <%= f.text_area :description, rows: 5, placeholder: "Write a brief description of your home", class: "form-control", required: true %>
        </div>
        <br />
        <div class="form-field">
          <%= f.text_field :address, placeholder: "Address", class: "form-control", required: true %>
        </div><br />


        <div class="row">
          <div class="col-6 select">
            <div class="field">
              <%= f.select :home_type, [["Apartment", "Apartment"], ["House", "House"], ["Hotel", "Hotel"], ["Resort", "Resort"], ["Villa", "Villa"]], id: "home_type", prompt: "Accommodation type", class: "form-control" %>
            </div>
          </div>
          <div class="col-6 select">
            <div class="field">
              <%= f.select :room_type, [["Single room", "Single room"], ["Double-room", "Double-room"], ["One-Bedroom", "One-Bedroom"]],
              id: "room_type", prompt: "Room_type...", class: "form-control" %>
            </div>
          </div>
        </div>
        <br />


        <div class="row">
          <div class="col-6 select">
            <div class="field">
              <%= f.select :bathroom, [["1", 1], ["2", 2], ["3", 3]],
              id: "bathroom", prompt: "Bathroom...", class: "form-control" %>
            </div>
          </div>

          <div class="col-6 select">
            <div class="field">
              <%= f.select :bedroom, [["1", 1], ["2", 2], ["3", 3]],
              id: "bedroom", prompt: "Bedroom...", class: "form-control" %>
            </div>
          </div>
        </div>
        <br />





        <div class="row">
          <div class="col-6 select">
            <div class="field">
              <%= f.select :adult, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["6", 6]],
              id: "adult", prompt: "Adult...", class: "form-control" %>
            </div>
          </div>
          <br /><br />


        <!--   <div class="col-6 select">
            <div class="field">
              <%= f.select :kids, [["1", 1], ["2", 2], ["3", 3], ["4", 4], ["6", 6]],
              id: "kids", prompt: "kids...", class: "form-control" %>
            </div>
          </div>
        </div> -->
          <br />
      
   
           
        <div class="col-6 select">
         <div class="field">
              <%= f.select :instant, Room.instants.map {|key, value| [key.humanize, key]}, selected: 'Instant', prompt: "Booking Type..", class: "form-control" %>
            </div>
          </div>
        </div>
      

          <br />

        <div class="form-field">
          <%= f.text_field :rate, placeholder: "Rate eg: $100", class: "form-control", required: true %>
        </div>
        <br />

        <div class="field">
          <%= f.label :photo %>
          <%= f.file_field :images, multiple: true %>
        </div>
        <br />

        <div class="field">
          <%= f.label :video %>
          <%= f.file_field :video %>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Add listing" , class: 'btn btn-danger' %>
        <div id='preview'></div>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>
</div>

app/views/host/rooms/show.html.erb
<div class="conatiner">
  <div class="row">
    <div class="col-md-3">
      <%= render 'host/rooms/room_menu' %>
    </div>


    <div class="box col-md-7">
      <% if @room.images.attached? %><%= image_tag @room.images.first, width: "100%", height: "450px" %>
      <% end %>
    </div>
  </div>
  <br />


  <div class="box col-md-6 offset-md-3">
    <%= link_to @room.listing_name, @room.web_url %>
    <br /><br />
    <p>Description:</p><%= @room.description %></p>

    <p><%= @room.rate %> <a>USD</a></p>
    <br />

    <%= link_to 'Preview As Guest...', room_path(@room), class: 'btn btn-warning' %>
  </div>
</div>
<br />




<div class="container">
  <div class="row text-center row-space-1">
    <div class="col-md-3 ">
      <i class="fa fa-home fa-2x"></i>
    </div>


    <div class="col-md-3 ">
      <i class="fa fa-user fa-2x"></i>
    </div>

    <div class="col-md-3 ">
      <i class="fa fa-bed fa-2x"></i>
    </div>

    <div class="col-md-3">
      <i class="fa fa-bath fa-2x"></i>
    </div>

  </div>

  <div class="row text-center">
    <div class="col-md-3"><%= @room.home_type %></div>
    <div class="col-md-3"><%= pluralize(@room.adult, "Adult") %></div>
    <div class="col-md-3"><%= pluralize(@room.bedroom, "Bedroom") %></div>
    <div class="col-md-3"><%= pluralize(@room.bathroom, "Bathroom") %></div>

  </div>
</div>
</div>
<br />



<%= render 'host/photos/photos_list' %>
<%= render 'host/rooms/modal' %>
<%= render 'host/rooms/roomratemodal' %>
<%= render 'host/rooms/editmodal' %>

<br />

</div>
</div>


</div>